### PR TITLE
Alternate background color for debug tables

### PR DESCRIPTION
**Pull request by kamui545**
Hi guys,

I added alternative style for odd rows to improve debug tables usability.

I had to rewrite the environments and SQL log tables to avoid some CSS problems due to the DOM (no thead/tbody tags). I hope it's not a problem that I removed the use of the HTML helper to construct those tables, I think it's more readable/flexible this way and more consistant regarding the tables from the others panels.

### CODE REVIEW

**Comment by lorenzo** [comment]
Could you paste a screenshot after the changes?

**Comment by lorenzo** [comment]
It looks like you changed the indentation style of the files, so it is difficult to see the real diff.

**Comment by markstory** [comment]
I thinl removing the helper usage is fine. It might be best to remove it in general, as I suspect there aee not many calls to that method anymore.

**Comment by kamui545** [comment]
screen shot 2015-01-02 at 00 33 27

Yeah I fixed some bad indentation as well.
And a syntax error in the CSS file (using // as comment instead of /* */)

**Comment by kamui545** [comment]
I removed the method to construct the table as it's not used anymore

**Comment by markstory** [comment]
Looks like there were tests for the removed method.

**Comment by kamui545** [comment]
Indeed, I forgot to run PHPUnit, my bad. I'll fix it

**Comment by kamui545** [comment]
Everything is green :+1:

**Comment by markstory** [comment]
Thanks @kamui545

**Pull request merged**
