### PR TITLE
Fix string to bool conversion

### PR DESCRIPTION
**Pull request by Fuxy22**
Countary to any sane person's expectations in php (bool)"false"
does not evaluate to "false" but "true" instead

### CODE REVIEW

**Comment by ravage84** [comment]
Proof: https://3v4l.org/b3p4n

**Comment by ravage84** [comment]
I see we do not have any tests for this controller:

https://github.com/cakephp/debug_kit/tree/e2d856ed7c504b80354038b22d6f342c13ac5145/tests/TestCase/Controller

Might be a good idea to add a regression test.
What do you think, @Fuxy22 ?

**Comment by Fuxy22** [comment]
Testing is good although I'm not very familiar with how its done in cakephp

**Comment by markstory** [comment]
Merging. I'll circle back and add tests for the entire controller later this week.

**Pull request merged**
