### PR TITLE
sqlite3 extension

### PR DESCRIPTION
**Pull request by mhf-ir**

### CODE REVIEW

**Comment by dereuromark** [comment]
This is not a requirement.
If sqlite is not present it will and can use a different configured DB, e.g. Mysql or Postgres.
It just needs "any" - you provided "none", that was the issue.

**Comment by dereuromark** [comment]
It is quite clearly mentioned in the README install instructions, as well, already:
https://github.com/cakephp/debug_kit#requirements
So closing then, as nothing is needed to be fixed.

**Comment by ndm2** [comment]
> [...] if you need to use a different database see the Database Configuration section below.

To be fair, there is no "_Database Configuration section_" below 😉  It should probably say something like "_see the Database Configuration section in the documentation linked below_", or directly link to it.

**Comment by dereuromark** [comment]
Done in https://github.com/cakephp/debug_kit/commit/b72d5e4ab458e706e3452f49f8f9c65e3ae7e627

**Pull request closed without merging**
