### PR TITLE
add sqlite to travis matrix

### PR DESCRIPTION
**Pull request by ceeram**

### CODE REVIEW

**Comment by ceeram** [comment]
debug_kit failed locally, but not on travis. Turned out it didnt run sqlite in travis build matrix.
The current fail woudl be fixed by #321 which leaves another fail with sqlite as posted in the comment of that PR

**Comment by markstory** [comment]
I think I took SQLite out originally as testing the schema insertion/removal breaks SQLite.

**Comment by ceeram** [comment]
Updated to make sqlite pass now

**Comment by bravo-kernel** [comment]
:clap:

**Pull request merged**
