### PR TITLE
fix for #582

### PR DESCRIPTION
**Pull request by highstrike**
fixing #585

### CODE REVIEW

**Comment by dereuromark** [comment]
Thank you! We will release a patch shortly.

**Comment by highstrike** [comment]
Thanks

**Comment by highstrike** [comment]
Sorry, I might have deleted the fork faster than travis could complete all the tests... not that it had anything to actually test since it still doesn't do `.ctp` files yet 😁

**Comment by dereuromark** [comment]
https://travis-ci.org/cakephp/debug_kit/builds/343351574 master is green. All good, tag released.

**Comment by markstory** [comment]
Thank you for fixing this @highstrike. Sorry for doing a bad merge conflict and not checking the code before tagging.

**Pull request merged**
