### PR TITLE
4.x move to Command class

### PR DESCRIPTION
**Pull request by saeideng**

### CODE REVIEW

**Comment by lorenzo** [comment]
Why did you remove the whitespace shell?

**Comment by saeideng** [comment]
>Why did you remove the whitespace shell?

because there are proper code linting tools
and I tested it ,  it did not work properly for me

**Comment by saeideng** [comment]
I can revert it 
it just says/shows for example 
```
!!!contains leading whitespaces: /src/Controller/PagesController.php
!!!contains trailing whitespaces: /src/Controller/PagesController.php
```

**Comment by lorenzo** [comment]
Yeah, I know the output. The idea is that it points you out to places where extra whitespace is dangerous.

**Comment by saeideng** [comment]
OK
https://travis-ci.org/cakephp/debug_kit/builds/444788571
I'll work on this PR, after opening  a PR for making compatible debug_kit with cache's  changes

**Comment by markstory** [comment]
@lorenzo I recommended it be removed as the whitespace issues can be caught by PHPCS now, and I think that it is a better tool for this kind of problem.

**Comment by saeideng** [comment]
let me know , should I revert `WhitespaceShell` ?

**Comment by saeideng** [comment]
so , this PR can merge

**Pull request merged**
