### PR TITLE
Displaying the results of the Ajax Request

### PR DESCRIPTION
**Pull request by gauravmak**
I am not sure if the issue was specific to me but the results of different tools were not being displayed on my screen.
It started working properly, like before, after this change.

### CODE REVIEW

**Comment by markstory** [comment]
So before this change did the panels not display?

**Comment by gauravmak** [comment]
No, I observed that Ajax response was proper but the div with id 'panel-content' was not getting updated with it.

**Comment by markstory** [comment]
So you couldn't see the panel contents?

**Comment by gauravmak** [comment]
Ya, I couldn't see the panel content so checked the process and could solve it with this change.

**Comment by markstory** [comment]
Interesting as I can see panel data in my local apps. I can see if this causes issues for me though.

**Comment by gauravmak** [comment]
It was working well before. I am not sure exactly when it stopped working but it was around time when I upgraded from 3.0.1 to 3.0.2. I am not sure.

Here is the ajax response for "Request" tool. It may help to debug.

```
{"error":null,"content":"<h2 class=\"panel-title\">Request<\/h2>\n<div class=\"panel-content\">\n    \n<h4>Routing Params<\/h4>\n<ul class=\"neat-array depth-0\"><li><strong>plugin<\/strong>(null)<\/li><li><strong>controller<\/strong>Suppliers<\/li><li><strong>action<\/strong>edit<\/li><li><strong>_ext<\/strong>(null)<\/li><li><strong>pass<\/strong>(array)<ul class=\"neat-array depth-1\"><li><strong>0<\/strong>16<\/li><\/ul><\/li><\/ul>\n<h4>Post data<\/h4>\n<p class=\"info\">No post data.<\/p>\n<h4>Query string<\/h4>\n<p class=\"info\">No querystring data.<\/p>\n<h4>Cookie<\/h4>\n    <ul class=\"neat-array depth-0\"><li><strong>CAKEPHP<\/strong>29dbpdhti3g9qcof40oj227sq3<\/li><li><strong>pos_pos_session<\/strong>a:10:{s:10:&quot;session_id&quot;;s:32:&quot;ae9cb3e634cdd2243ef17fa3b00d795f&quot;;s:10:&quot;ip_address&quot;;s:3:&quot;::1&quot;;s:10:&quot;user_agent&quot;;s:109:&quot;Mozilla\/5.0 (Windows NT 6.1; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/42.0.2311.152 Safari\/537.36&quot;;s:13:&quot;last_activity&quot;;i:1432011235;s:9:&quot;user_data&quot;;s:0:&quot;&quot;;s:8:&quot;identity&quot;;s:16:&quot;admin@5339.co.uk&quot;;s:8:&quot;username&quot;;s:13:&quot;Administrator&quot;;s:5:&quot;email&quot;;s:16:&quot;admin@5339.co.uk&quot;;s:7:&quot;user_id&quot;;s:1:&quot;1&quot;;s:14:&quot;old_last_login&quot;;s:10:&quot;1431955323&quot;;}2bb25b8e3954e3090f62e00c38650b23<\/li><li><strong>PHPSESSID<\/strong>c1mi9soh6qo47kqrh2l8m6uu63<\/li><\/ul><\/div>\n"}
```

**Comment by gauravmak** [comment]
As there are 2 things - error and content. I tried setting the content as the output and it worked.

**Comment by markstory** [comment]
Where is that error key coming from? That is not part of the response debugkit should be generating. The requests that debugkit makes should return HTML blobs not JSON data. Perhaps you have application code that is converting the responses?

**Comment by gauravmak** [comment]
Oh, I see. I am really sorry for this. I am actually using [Ajax Plugin](https://github.com/dereuromark/cakephp-ajax) in my app. 

I had to make some changes in it according to the project requirements so I have put the code inside my app instead of keeping it as a plugin. I am not a CakePHP pro and I am still not sure why the debugkit is also using the **View/AjaxView.php** before retuning (rendering) the result.

As per the plugin code, I am specifically telling the app to use AjaxView in my **Controller/Component/AjaxComponent.php** which is loaded only in my **AjaxController.php**
```
$this->Controller->viewClass = 'Ajax';
```
So, I thought it wouldn't affect others.
May I have your expert guidance on how to tackle this and make sure that plugins do not use it?

Thank you.

**Pull request closed without merging**
