### PR TITLE
Branding update

### PR DESCRIPTION
**Pull request by markstory**
Update DebugKit to reflect the new project branding. There aren't any functional changes, just a new coat of pixels.

### Collapsed icon

screen shot 2016-07-31 at 22 20 22

### Updated Timer Panel

screen shot 2016-07-31 at 22 21 22

### Updated History mode

screen shot 2016-07-31 at 22 22 09

### CODE REVIEW

**Comment by antograssiot** [comment]
👍 I've tested it and just wonder if the icon deserved a better definition..

**Comment by antograssiot** [comment]
also did you consider using Raleway in the sidebar like so ? just a proposal, your designer skills are way better than mine 😛 
capture d ecran 2016-08-02 a 20 28 40

**Comment by markstory** [comment]
@antograssiot I didn't consider that. I agree it looks better. I'll update it tonight.

**Comment by markstory** [comment]
@antograssiot Fixed the fonts and made the icon less aliased.

**Comment by antograssiot** [comment]
looks good ! 👏

**Comment by ADmad** [comment]
I would prefer if debugkit did not have any external dependencies like the google fonts. It becomes a tad annoying when you have to develop without internet connection and the page loading stutters waiting for the external urls to timeout.

**Comment by markstory** [comment]
@ADmad I can try and find a offline source for Raleway.

**Pull request merged**
