### PR TITLE
Run composer normalize over composer.json

### PR DESCRIPTION
**Pull request by dereuromark**
Auto created via toolbox app.

- Runs https://github.com/ergebnis/composer-normalize over composer.json

### CODE REVIEW

**Comment by dereuromark** [comment]
If this is something we want to do to normalize it across all repos, I can run the tool over all relevant repos.
Just let me know.

There might be more merge conflicts at the start, but then should minimize afterwards.

**Review by ravage84 — COMMENTED** [review]
While I do like uniformity most often, I'm not sure I like it in this "opinionated" way. 🤷

**Comment by dereuromark** [comment]
Is it? Afaik it aligns itself according to the underlying [JSON schema](https://getcomposer.org/schema.json)
So it just follows what composer dictates as Schema it seems.

**Comment by othercorey** [comment]
Looks ok to me. I remember doing this manually once, but I guess I never committed.

**Comment by LordSimal** [comment]
The only thing that's weird to me is the position of the `suggest` block. Everything is fine by me 👍🏻 
But I guess we can all get used to it. Would love to see it across all our repos AND a github CI check

**Comment by dereuromark** [comment]
Well, we can reach out to composer and ask them to fix up the order as per our suggestions - pun intended :)
Before we further modify more repos.

As for the CI check: Might be a bit overkill, so often we will not change the structure as a whole.

**Pull request merged**
